---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/GIF
  label: Gif
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/blog_links
  label: Blog links
  create: all
  match: "**/*"
- type: directory
  path: content/dev_manual
  label: Dev manual
  create: all
  match: "**/*"
- type: directory
  path: content/facilitators_guide
  label: Facilitators guide
  create: all
  match: "**/*"
- type: directory
  path: content/guides
  label: Guides
  create: all
  match: "**/*"
- type: directory
  path: content/legal
  label: Legal
  create: all
  match: "**/*"
- type: directory
  path: content/newsletter_content
  label: Newsletter content
  create: all
  match: "**/*"
- type: directory
  path: content/product_roadmap_images
  label: Product roadmap images
  create: all
  match: "**/*"
- type: directory
  path: content/subscriptions
  label: Subscriptions
  create: all
  match: "**/*"
- type: directory
  path: content/testimonials
  label: Testimonials
  create: all
  match: "**/*"
- type: directory
  path: content/user_manual
  label: User manual
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
